import React, { useEffect, useState } from 'react';
import { Skeleton } from '@mui/material';
import { sessionsApi } from '../../api/sessions';
import { Insight } from '../../types';
import { colors, fonts } from '../../theme/tokens';
import { Panel, Mono, Label } from '../../components/apex';

interface Props {
  sessionId: number;
}

const SEVERITY_TAG: Record<
  Insight['severity'],
  { label: string; color: string; bg: string }
> = {
  info: {
    label: 'INFO',
    color: colors.accent,
    bg: 'rgba(62, 197, 209, 0.08)',
  },
  success: {
    label: 'PB',
    color: colors.green,
    bg: 'rgba(38, 208, 124, 0.08)',
  },
  warning: {
    label: 'WARN',
    color: colors.yellow,
    bg: 'rgba(255, 194, 51, 0.08)',
  },
  error: {
    label: 'ALERT',
    color: colors.red,
    bg: 'rgba(255, 79, 79, 0.08)',
  },
};

const InsightsPanel: React.FC<Props> = ({ sessionId }) => {
  const [insights, setInsights] = useState<Insight[] | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    setLoading(true);
    setError(null);
    sessionsApi
      .insights(sessionId)
      .then((r) => setInsights(r.insights))
      .catch((e: any) =>
        setError(e?.response?.data?.message || 'Could not generate insights'),
      )
      .finally(() => setLoading(false));
  }, [sessionId]);

  if (loading) {
    return (
      <Panel title="Automatic findings" padding={16}>
        <Skeleton variant="rectangular" height={40} sx={{ mb: 1, bgcolor: colors.surface2 }} />
        <Skeleton variant="rectangular" height={40} sx={{ mb: 1, bgcolor: colors.surface2 }} />
        <Skeleton variant="rectangular" height={40} sx={{ bgcolor: colors.surface2 }} />
      </Panel>
    );
  }

  if (error) {
    return (
      <Panel title="Automatic findings" padding={16}>
        <div
          style={{
            padding: '10px 14px',
            border: `1px solid ${colors.yellow}`,
            color: colors.yellow,
            fontFamily: fonts.mono,
            fontSize: 11,
            letterSpacing: '0.6px',
          }}
        >
          {error}
        </div>
      </Panel>
    );
  }

  if (!insights || insights.length === 0) {
    return null;
  }

  return (
    <Panel
      title="Automatic findings"
      right={
        <Mono style={{ color: colors.textMute }}>
          {insights.length} insight{insights.length !== 1 ? 's' : ''}
        </Mono>
      }
      padding={16}
    >
      <Mono
        style={{
          fontSize: 11,
          color: colors.textMute,
          letterSpacing: '0.3px',
          marginBottom: 14,
          lineHeight: 1.5,
          display: 'block',
        }}
      >
        Generated by statistical analysis: theoretical best, degradation, consistency,
        outliers, stint comparisons and weak sectors.
      </Mono>
      <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
        {insights.map((ins, idx) => {
          const tag = SEVERITY_TAG[ins.severity];
          return (
            <div
              key={idx}
              style={{
                display: 'grid',
                gridTemplateColumns: '4px 70px 1fr',
                alignItems: 'stretch',
                background: tag.bg,
                border: `1px solid ${colors.border}`,
                borderLeft: `2px solid ${tag.color}`,
              }}
            >
              <div />
              <div
                style={{
                  display: 'flex',
                  flexDirection: 'column',
                  alignItems: 'flex-start',
                  justifyContent: 'center',
                  padding: '10px 0 10px 4px',
                  gap: 4,
                }}
              >
                {ins.icon && (
                  <span
                    style={{
                      fontSize: 16,
                      lineHeight: 1,
                      color: tag.color,
                    }}
                  >
                    {ins.icon}
                  </span>
                )}
                <Label tone="mute" size="micro" style={{ color: tag.color }}>
                  {tag.label}
                </Label>
              </div>
              <div style={{ padding: '10px 12px 10px 4px' }}>
                <div
                  style={{
                    fontSize: 13,
                    fontWeight: 600,
                    color: colors.text,
                    marginBottom: 3,
                    fontFamily: fonts.sans,
                  }}
                >
                  {ins.title}
                </div>
                <div
                  style={{
                    fontSize: 12,
                    color: colors.textDim,
                    fontFamily: fonts.sans,
                    lineHeight: 1.4,
                  }}
                >
                  {ins.detail}
                </div>
              </div>
            </div>
          );
        })}
      </div>
    </Panel>
  );
};

export default InsightsPanel;
